### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by 3DExtended** [Jellevermandere/BasicCharacterUnity#1]
Hey!

I came across your youtube channel and was pretty happy to find a repository attached to your video ^^ Thanks for the great work!

Would you mind adding an license file to it as well? 

Thanks again and keep it up!

**Comment by michaelbdavidson7** [comment]
I was looking for this as well, though I found example code from the Unity docs that helped me instead. I also hope the author will make it MIT License for others though.

**Comment by Jellevermandere** [comment]
I added an MIT licence!
